-- UnderSync is a single-team deployment for FRC 1156 - Under Control.
DO $$
BEGIN
  IF (SELECT count(*) FROM "teams") > 1 THEN
    RAISE EXCEPTION 'Cannot convert to single-team mode while more than one team exists';
  END IF;
END;
$$;

DROP TRIGGER "tasks_check_people" ON "tasks";
DROP FUNCTION undersync_check_task_people();
DROP TRIGGER "part_user_assignments_check_team" ON "part_user_assignments";
DROP TRIGGER "task_parts_check_team" ON "task_parts";
DROP FUNCTION undersync_check_part_relation_team();
DROP TRIGGER "custom_field_values_check_definition" ON "custom_field_values";
DROP FUNCTION undersync_check_custom_field_value();
DROP TRIGGER "parts_generate_tracking_code" ON "parts";
DROP FUNCTION undersync_generate_part_tracking_code();

DROP INDEX "users_team_id_status_idx";
DROP INDEX "users_team_name_ci_key";
DROP INDEX "seasons_team_id_code_key";
DROP INDEX "subsystems_team_id_code_key";
DROP INDEX "manufacturing_methods_team_id_code_key";
DROP INDEX "materials_team_id_code_key";
DROP INDEX "parts_team_id_kind_status_idx";
DROP INDEX "parts_team_id_season_id_sequence_value_key";
DROP INDEX "custom_field_definitions_team_id_entity_type_key_key";

ALTER TABLE "users" DROP CONSTRAINT "users_team_id_fkey";
ALTER TABLE "seasons" DROP CONSTRAINT "seasons_team_id_fkey";
ALTER TABLE "subsystems" DROP CONSTRAINT "subsystems_team_id_fkey";
ALTER TABLE "manufacturing_methods" DROP CONSTRAINT "manufacturing_methods_team_id_fkey";
ALTER TABLE "materials" DROP CONSTRAINT "materials_team_id_fkey";
ALTER TABLE "part_number_sequences" DROP CONSTRAINT "part_number_sequences_team_id_fkey";
ALTER TABLE "parts" DROP CONSTRAINT "parts_team_id_fkey";
ALTER TABLE "custom_field_definitions" DROP CONSTRAINT "custom_field_definitions_team_id_fkey";

ALTER TABLE "part_number_sequences" DROP CONSTRAINT "part_number_sequences_pkey";

ALTER TABLE "users" DROP COLUMN "team_id";
ALTER TABLE "seasons" DROP COLUMN "team_id";
ALTER TABLE "subsystems" DROP COLUMN "team_id";
ALTER TABLE "manufacturing_methods" DROP COLUMN "team_id";
ALTER TABLE "materials" DROP COLUMN "team_id";
ALTER TABLE "part_number_sequences" DROP COLUMN "team_id";
ALTER TABLE "parts" DROP COLUMN "team_id";
ALTER TABLE "custom_field_definitions" DROP COLUMN "team_id";

DROP TABLE "teams";

ALTER TABLE "part_number_sequences" ADD CONSTRAINT "part_number_sequences_pkey" PRIMARY KEY ("season_id");
CREATE UNIQUE INDEX "users_name_ci_key" ON "users" (lower("name"));
CREATE INDEX "users_status_idx" ON "users" ("status");
CREATE UNIQUE INDEX "seasons_code_key" ON "seasons" ("code");
CREATE UNIQUE INDEX "subsystems_code_key" ON "subsystems" ("code");
CREATE UNIQUE INDEX "manufacturing_methods_code_key" ON "manufacturing_methods" ("code");
CREATE UNIQUE INDEX "materials_code_key" ON "materials" ("code");
CREATE INDEX "parts_kind_status_idx" ON "parts" ("kind", "status");
CREATE UNIQUE INDEX "parts_season_id_sequence_value_key" ON "parts" ("season_id", "sequence_value");
CREATE UNIQUE INDEX "custom_field_definitions_entity_type_key_key" ON "custom_field_definitions" ("entity_type", "key");

CREATE OR REPLACE FUNCTION undersync_generate_part_tracking_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  season_code text;
  subsystem_code text;
  method_code text;
  material_code text;
  allocated_sequence integer;
BEGIN
  IF NEW.tracking_code IS NOT NULL
     OR NEW.sequence_value IS NOT NULL
     OR NEW.origin_team_number IS NOT NULL
     OR NEW.origin_season_code IS NOT NULL
     OR NEW.origin_subsystem_code IS NOT NULL
     OR NEW.origin_manufacturing_code IS NOT NULL
     OR NEW.origin_material_code IS NOT NULL THEN
    RAISE EXCEPTION 'Parts Tracking IDs and origin fields are generated by UnderSync';
  END IF;

  SELECT "code" INTO STRICT season_code FROM "seasons" WHERE "id" = NEW.season_id;
  SELECT "code" INTO STRICT subsystem_code FROM "subsystems" WHERE "id" = NEW.subsystem_id;

  IF NEW.kind = 'MANUFACTURED' THEN
    SELECT "code" INTO STRICT method_code FROM "manufacturing_methods" WHERE "id" = NEW.manufacturing_method_id;
    SELECT "code" INTO STRICT material_code FROM "materials" WHERE "id" = NEW.material_id;
  ELSE
    method_code := 'COTS';
    material_code := 'NA';
  END IF;

  INSERT INTO "part_number_sequences" ("season_id", "next_value")
  VALUES (NEW.season_id, 2)
  ON CONFLICT ("season_id")
  DO UPDATE SET "next_value" = "part_number_sequences"."next_value" + 1
  RETURNING "next_value" - 1 INTO allocated_sequence;

  NEW.sequence_value := allocated_sequence;
  NEW.origin_team_number := 1156;
  NEW.origin_season_code := season_code;
  NEW.origin_subsystem_code := subsystem_code;
  NEW.origin_manufacturing_code := method_code;
  NEW.origin_material_code := material_code;
  NEW.tracking_code := '1156-' || season_code || '-' || subsystem_code || '-' || method_code || '-' || material_code || '-' || lpad(allocated_sequence::text, 3, '0');
  RETURN NEW;
END;
$$;

CREATE TRIGGER "parts_generate_tracking_code"
BEFORE INSERT ON "parts"
FOR EACH ROW EXECUTE FUNCTION undersync_generate_part_tracking_code();

CREATE OR REPLACE FUNCTION undersync_check_custom_field_value()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  defined_entity "CustomFieldEntityType";
  defined_type "CustomFieldValueType";
BEGIN
  SELECT "entity_type", "value_type"
    INTO STRICT defined_entity, defined_type
    FROM "custom_field_definitions" WHERE "id" = NEW.definition_id AND "active" = true;

  IF NEW.user_id IS NOT NULL AND defined_entity <> 'USER' THEN
    RAISE EXCEPTION 'Custom field target type does not match definition';
  ELSIF NEW.task_id IS NOT NULL AND defined_entity <> 'TASK' THEN
    RAISE EXCEPTION 'Custom field target type does not match definition';
  ELSIF NEW.part_id IS NOT NULL AND defined_entity <> 'PART' THEN
    RAISE EXCEPTION 'Custom field target type does not match definition';
  END IF;

  IF (defined_type IN ('TEXT', 'DATE', 'SELECT') AND jsonb_typeof(NEW.value) <> 'string')
     OR (defined_type = 'NUMBER' AND jsonb_typeof(NEW.value) <> 'number')
     OR (defined_type = 'BOOLEAN' AND jsonb_typeof(NEW.value) <> 'boolean') THEN
    RAISE EXCEPTION 'Custom field value JSON type does not match definition';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "custom_field_values_check_definition"
BEFORE INSERT OR UPDATE ON "custom_field_values"
FOR EACH ROW EXECUTE FUNCTION undersync_check_custom_field_value();
